version: "3"

services:
  webserver:
    build: 
      context: ./webserver
    container_name: 'webserver'
    restart: 'always'
    ports:
      - "85:80"
      - "443:443"
    links:
      - mysql
    volumes: 
      - ${DOCUMENT_ROOT-.}:/var/www/html
      - ${VHOSTS_DIR-./vhosts}:/etc/apache2/sites-enabled
      - ${LOG_DIR-./logs/apache2}:/var/log/apache2
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dvwa
      MYSQL_USER: dvwa
      MYSQL_PASSWORD: dvwa